### PR TITLE
DO NOT🍩 MERGE Add stateless rest server.

### PR DESCRIPTION
**Pull request by qurben**
The rest server publishes events on the request topic, which services
can consume from and create events on the response topic. This is read
by the rest server and a response is created for the user.

The request and response topics could be partitioned on request id and
the producers could have some way of generating ids which will lead
back to their own instance.

The payloads are of a specific type and using that the right function can be 
called for handling a specific payload, payloads should be specific for a service
and only a single response should be sent on the response topic 
(subsequent events are ignored).

Still a draft because I am not 100% sure if this is the right approach. And
it is currently only implemented for creating users. It also still needs
Kubernetes definitions.

See also [Stateless REST API](https://github.com/casperboone/wdm-kafka-microservices/wiki/Stateless-REST-API) on the wiki.

diagram

### CODE REVIEW

**Comment by qurben** [comment]
# Considerations

It seems hard to create ad-hoc listeners on topics, I played around with creating and deleting listeners when a response is expected.

Having different topics for different actions makes it become very complex very fast. All the listeners need to be created and managed.

**Comment by gandreadis** [comment]
@qurben I share your concerns! The approach is the right one, but because we have so many topics, this might become a mess. I'm now looking into whether we can merge topics (which would also might make persistence/event-sourcing easier)

**Comment by qurben** [comment]
It is fairly easy with spring kafka to have objects of multiple types on a single topic (as done in [`Rest.java`](https://github.com/casperboone/wdm-kafka-microservices/blob/adb62e738bbc2670f618dd29e44f1a5e2c94633f/users/src/main/java/nl/tudelft/wdm/group1/users/events/Rest.java))

**Comment by qurben** [comment]
e2e works again :D

**Comment by qurben** [comment]
Superseded bij #46

**Pull request closed without merging**
