### PR TITLE
WIP: Kafka partitioning with payments

### PR DESCRIPTION
**Pull request by gandreadis**
Depends on #67

### CODE REVIEW

**Comment by qurben** [comment]
Well, lets add some more ram to docker 😁

**Comment by qurben** [comment]
I am seeying some errors in the logs. Not sure yet why they are there

**Comment by qurben** [comment]
`OrderConsumer` is not yet setup to handle the partitioning.

**Comment by qurben** [comment]
Same for `UserConsumer`

**Comment by gandreadis** [comment]
Well, the OrderConsumer also shouldn't be setup for that, right? We don't partition orders

**Comment by gandreadis** [comment]
I've fixed the UserConsumer

**Comment by qurben** [comment]
The UsersTopics credit subtracted for payment success/fail topicsare set to three partitions in the users service. This is probably not how it should be as they are not consumed from in the users service.

**Comment by qurben** [comment]
I am getting some errors about rebalancing:

```
2019-06-10 08:31:29.918 ERROR 6 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-10, groupId=payments_group] Offset commit failed on partition paymentDeleted-1 at offset 0: The coordinator is not aware of this member.
2019-06-10 08:31:29.918  WARN 6 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-10, groupId=payments_group] Asynchronous auto-commit of offsets {paymentDeleted-1=OffsetAndMetadata{offset=0, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
```

**Comment by gandreadis** [comment]
About the three partitions: In theory, yes, but we'll just assume for now that NUM_PARTITIONS is the same for all services with partitions

**Comment by gandreadis** [comment]
Ah, you mean where they should be set up? (so rather in the payments service?)

**Comment by qurben** [comment]
Well you only care about the number of partitions when you consume from a topic. When one service sets the partitions on a topic and there are consumers of that topic in other services the entire application will break because the consumer from that order service will only consume from a single partition.

**Comment by gandreadis** [comment]
Closing due to implementation issues

**Pull request closed without merging**
