### PR TITLE
Add stateless rest server for users

### PR DESCRIPTION
**Pull request by qurben**
Because all at once is a bit much.

### CODE REVIEW

**Comment by gandreadis** [comment]
Seems like you forgot to add an implementation for the `GET /credit` route, pushing a fix in a couple of minutes :)

**Comment by qurben** [comment]
Q: whats the point of that route if it returns a user?

**Comment by gandreadis** [comment]
I agree, we can also remove it. I'm guessing we had it because it's simply in the specs. I'd say for now let's just adhere to the specs, even though they may be superfluous

**Comment by gandreadis** [comment]
On a second thought, let's remove it. I really don't see a point in having a separate route for this, either.

**Pull request merged**
